### PR TITLE
SSL: Fix wildcard support

### LINKED ISSUE #271: Missing wildcard support in SSL hostname verification
The initial support added in commit 961cf5408baf17944edab2bf771afb90471c4262 (@theopolis) compares plain strings only.

### PR DESCRIPTION
**Pull request by theopolis**
Fixes #271

### CODE REVIEW

**Comment by ismaell** [comment]
This only matches a wildcard for the entire first label, which isn't enough. I don't want to go crazy on the implementation, but at least it should match a single wildcard per label, anywhere it is.

Also, the code looks uglier now :/.

Let me try to come up with something more generic using libc functions (also should be faster).

**Comment by ismaell** [comment]
Oh, I see the [RFC](https://tools.ietf.org/html/rfc6125#section-6.4.3) is a little bit tricky

**Comment by ismaell** [comment]
I've just pushed a more comprehensive implementation.
Commit 480e26e694eb0a9cd895bf218c024332f6ec2e73.
Check it out.

**Comment by theopolis** [comment]
How is `dn_match` used? I left a comment here: https://github.com/axel-download-accelerator/axel/commit/480e26e694eb0a9cd895bf218c024332f6ec2e73#r38082381

**Comment by ismaell** [comment]
@theopolis I realize now that the patching  isn't straightforward, but since it was a little bit too hacky I didn't push it. I'm cleaning it up now for submission.

**Comment by ismaell** [comment]
@theopolis I've just pushed the rest to cert-hostname-check branch.

**Comment by ismaell** [comment]
`dn_match` is missing a check, in case the first is an u-label.

**Comment by ismaell** [comment]
Superseded by proposed update: https://github.com/axel-download-accelerator/axel/tree/cert-hostname-check

**Pull request closed without merging**
