### PR TITLE
Create footnotes in CONTRIBUTING.md and README.md

### PR DESCRIPTION
**Pull request by jeongukjae**
I found that footnotes are not shown properly.

### CODE REVIEW

**Comment by ismaell** [comment]
It renders correctly for me, which MD parser are you using?

**Comment by jeongukjae** [comment]
I'm using GitHub. You can see differences in a section "1. Help this project" of [this](https://github.com/axel-download-accelerator/axel/blob/master/README.md) and [this](https://github.com/jeongukjae/axel/blob/master/README.md). I thought those are footnotes, so edited like that.

**Comment by ismaell** [comment]
Ah, I see what you mean now... but "^N" isn't rendering correctly for me...

**Comment by jeongukjae** [comment]
Oh you are right. I will remove `^`.

**Comment by ismaell** [comment]
Confirmed. Github doesn't support footnotes. Ideas? It doesn't look right the way it is now... but also it shouldn't depend on github...

**Comment by jeongukjae** [comment]
I think it is possible to use superscript tag but messy. So it might be better to keep or add a new line between each footnotes.

**Pull request merged**
