### PR TITLE
Minor improvements in README.md

### PR DESCRIPTION
**Pull request by junaid-ali**
* Updated build dependencies
* Remove a typo in final build command
* Added steps for building on Ubuntu 16.04 for reference

### CODE REVIEW

**Comment by ismaell** [comment]
@junaid-ali Thanks. Looks Fine. Would you mind to sign-off the commit?

Regards.

**Comment by junaid-ali** [comment]
Thanks @ismaell for the review. I have signed off the changes by creating a new commit on top of the previous one (please suggest if it is not the recommended way).

**Comment by ismaell** [comment]
@junaid-ali it's meant to provide a chain of responsibility, so it's applied commit-by-commit, you must ammend the original commit and force-push to the same branch to update the pull request.

**Comment by junaid-ali** [comment]
@ismaell thanks, I didn't know about the `--force` flag with `git push`.

**Comment by ismaell** [comment]
@junaid-ali Thanks.

**Pull request merged**
