### PR TITLE
conn: Make HTTPS the default

### PR DESCRIPTION
**Pull request by Jason23347**

### CODE REVIEW

**Comment by Jason23347** [comment]
I'm not sure whether fallback to http is needed. @ismaell Could you please give me some suggestions?

**Comment by ismaell** [comment]
Indeed, it must fallback to HTTP to keep it compatible, so this requires some rework.

**Comment by ismaell** [comment]
Woooow, not so fast, it can only degrade to HTTP if the URL didn't had the protocol scheme.

**Comment by Jason23347** [comment]
Ok, I will fix it later.

**Comment by ismaell** [comment]
This approach is a bad idea.

An acceptable alternative would be simply to check for the URL scheme, and if it isn't here, produce two `conn_t` from it instead of one, that way the normal flow of the program should take care of the fallback.

**Pull request closed without merging**
